name = "QuantumDynamicInconsistencyModels"
uuid = "0ed30ee8-6cef-4eac-8e89-7848059aa71e"
authors = ["itsdfish"]
version = "0.3.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
Distributions = "0.25.0"
LinearAlgebra = "1"
PrettyTables = "3.0"
Random = "1"
SafeTestsets = "0.1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
