[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumDynamicInconsistencyModels = "0ed30ee8-6cef-4eac-8e89-7848059aa71e"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Documenter = "1"
Pigeons = "0.4.0"
Plots = "1"
StatsPlots = "0.15.0"
Turing = "0.33.0"
